site_name: LavaDocs

nav:
  - Home: yangemalee.md
  - About: about.md

theme:
  name: null
  custom_dir: custom_theme
  static_templates:
    - 404.html

  include_search_page: true
  search_index_only: false
